"""initial schema

Revision ID: 29d240a16429
Revises: 
Create Date: 2026-06-05 20:33:27.727799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d240a16429'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('signal_value', sa.Float(), nullable=True),
    sa.Column('signal_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_factory_created', 'events', ['factory_id', 'created_at'], unique=False)
    op.create_index('ix_events_factory_type', 'events', ['factory_id', 'event_type'], unique=False)
    op.create_table('factories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.JSON(), nullable=True),
    sa.Column('approved_action', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approval_timestamp', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('layer_latencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_factory_created', 'decisions', ['factory_id', 'created_at'], unique=False)
    op.create_index('ix_decisions_factory_status', 'decisions', ['factory_id', 'status'], unique=False)
    op.create_table('approval_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('approver_role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_trail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_decision', 'approval_workflows', ['decision_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_decision', 'audit_logs', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_decision', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_decision', table_name='approval_workflows')
    op.drop_table('approval_workflows')
    op.drop_index('ix_decisions_factory_status', table_name='decisions')
    op.drop_index('ix_decisions_factory_created', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('factories')
    op.drop_index('ix_events_factory_type', table_name='events')
    op.drop_index('ix_events_factory_created', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
